name: Deploy Content to law-sent-us-01 [a42d21f7-4790-431a-902a-26a6d2113a57]
# Note: This workflow will deploy everything in the root directory.
# To deploy content only from a specific path (for example SentinelContent):
#   1. Add the target path to the "paths" property like such
#    paths:
#    - 'SentinelContent/**'
#    - '!.github/workflows/**'
#    - '.github/workflows/sentinel-deploy-a42d21f7-4790-431a-902a-26a6d2113a57.yml'
#   2. Append the path to the directory environment variable below
#       directory: '${{ github.workspace }}/SentinelContent'

on:
  push:
    branches: [ main ]
    paths:
    - '**'
    - '!.github/workflows/**'  # this filter prevents other workflow changes from triggering this workflow
    - '.github/workflows/sentinel-deploy-a42d21f7-4790-431a-902a-26a6d2113a57.yml'

jobs:
  deploy-content:
    runs-on: windows-latest
    env:
      resourceGroupName: 'rg-law-us-01'
      workspaceName: 'law-sent-us-01'
      workspaceId: '58f02ae2-bc51-47e5-ae18-9d07d77a05e7'
      directory: '${{ github.workspace }}'
      cloudEnv: 'AzureCloud'
      contentTypes: 'Workbook,Parser,HuntingQuery,AutomationRule,AnalyticsRule,Playbook'
      branch: 'main'
      sourceControlId: 'a42d21f7-4790-431a-902a-26a6d2113a57'
      rootDirectory: '${{ github.workspace }}'
      githubAuthToken: ${{ secrets.GITHUB_TOKEN }}
      smartDeployment: 'true'
    permissions:
      contents: write
      id-token: write # Require write permission to Fetch an OIDC token.

    steps:
    - name: Login to Azure (Attempt 1)
      continue-on-error: true
      id: login1
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_a42d21f74790431a902a26a6d2113a57 }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_a42d21f74790431a902a26a6d2113a57 }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_a42d21f74790431a902a26a6d2113a57 }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 1 failed
      if: ${{ steps.login1.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 2)
      continue-on-error: true
      id: login2
      uses: azure/login@v2
      if: ${{ steps.login1.outcome=='failure' }}
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_a42d21f74790431a902a26a6d2113a57 }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_a42d21f74790431a902a26a6d2113a57 }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_a42d21f74790431a902a26a6d2113a57 }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 2 failed
      if: ${{ steps.login2.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 3)
      continue-on-error: false
      id: login3
      uses: azure/login@v2
      if: ${{ steps.login2.outcome=='failure'  }}
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_a42d21f74790431a902a26a6d2113a57 }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_a42d21f74790431a902a26a6d2113a57 }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_a42d21f74790431a902a26a6d2113a57 }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Checkout
      uses: actions/checkout@v3

    - name: Deploy Content to Microsoft Sentinel
      uses: azure/powershell@v2
      with:
        azPSVersion: 'latest'
        inlineScript: |
          ${{ github.workspace }}//.github/workflows/azure-sentinel-deploy-a42d21f7-4790-431a-902a-26a6d2113a57.ps1